"""empty message

Revision ID: dc09f6db4fad
Revises: f255fd0ed22f
Create Date: 2018-06-26 11:46:25.974110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc09f6db4fad'
down_revision = 'f255fd0ed22f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('createtime', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'createtime')
    # ### end Alembic commands ###
